# Generated by Django 6.1.1 on 2026-10-06 02:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Pergunta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "texto",
                    models.CharField(max_length=200, verbose_name="texto da pergunta"),
                ),
                (
                    "publicada_em",
                    models.DateTimeField(verbose_name="data de publicação"),
                ),
            ],
            options={
                "verbose_name": "pergunta",
                "verbose_name_plural": "perguntas",
                "ordering": ["-publicada_em"],
            },
        ),
        migrations.CreateModel(
            name="Opcao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "texto",
                    models.CharField(max_length=200, verbose_name="texto da opção"),
                ),
                ("votos", models.IntegerField(default=0, verbose_name="votos")),
                (
                    "pergunta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="opcoes",
                        to="tutorial_enquetes.pergunta",
                    ),
                ),
            ],
            options={
                "verbose_name": "opção",
                "verbose_name_plural": "opções",
            },
        ),
    ]
